### ISSUE TITLE
ERROR: CheckBlock: Consensus::CheckBlockHeader: high-hash, proof of work failed (code 16)

### ISSUE THREAD

**Issue by jeromemorignot** [RavenCommunity/kawpow-stratum-pool#2]
When mining I'm getting a lot of errors in the debug.log of the Raven daemon :
2020-05-27 17:16:13 ERROR: ProcessNewBlock: AcceptBlock FAILED (proof of work failed)
2020-05-27 17:16:13 ERROR: CheckBlock: Consensus::CheckBlockHeader: high-hash, proof of work failed (code 16)
I was able to mine some blocks...but seems weird?
Thank you

**Comment by jeromemorignot** [comment]
I actually found a solution by using the kawpowd validator.....it would have been helpful to have it documented :)

**Comment by Coinpony** [comment]
> I actually found a solution by using the kawpowd validator.....it would have been helpful to have it documented :)
how ? 
Can you see the solution in more detail?

**Comment by le2Ks** [comment]
> 
> 
> I actually found a solution by using the kawpowd validator.....it would have been helpful to have it documented :)

How did you proceed? I don'T understand what is the Kawpowd validator in that context o-o

**Comment by jalalalaskka** [comment]
I don'T understand what is the Kawpowd validator ?

**Comment by edradev** [comment]
> I actually found a solution by using the kawpowd validator.....it would have been helpful to have it documented :)

I'm facing the exact problem. Please share your way to fix it.

**Comment by jalalalaska** [comment]
There is a monopoly

**Comment by edradev** [comment]
always do. someone helping them and then they do not sharing the solution

**Comment by jalalalaska** [comment]
You must pay to get the solution

**Comment by jeromemorignot** [comment]
LOL - You are so funny you guys @jalalalaska  @edradev - I spent some time analyzing the code to understand how it works in order to find the solution. Nobody gave me the solution :)

**Comment by jalalalaska** [comment]
Did you find the solution?

**Comment by jeromemorignot** [comment]
> Did you find the solution?

Yes.

**Comment by jalalalaska** [comment]
Post solution

**Comment by edradev** [comment]
He wont post it, leave him to be happy

**Comment by jalalalaska** [comment]
you are right
